package codegen

import (
	"fmt"
	"strings"
)

// renderTemplate produces a minimal compiling-shaped source skeleton for the
// given language/kind. Unknown combinations fall back to a documented module
// stub so scaffolding never fails on a new extension.
func renderTemplate(lang, kind, name, namespace string, imports []string) string {
	switch lang {
	case "go":
		return goTemplate(kind, name, namespace, imports)
	case "python":
		return pythonTemplate(kind, name, imports)
	case "typescript", "javascript":
		return tsTemplate(lang, kind, name, imports)
	case "java":
		return javaTemplate(kind, name, namespace, imports)
	case "kotlin":
		return kotlinTemplate(kind, name, namespace, imports)
	case "csharp":
		return csharpTemplate(kind, name, namespace, imports)
	case "swift":
		return swiftTemplate(kind, name, imports)
	case "php":
		return phpTemplate(kind, name, namespace, imports)
	case "rust":
		return rustTemplate(kind, name, imports)
	case "c", "cpp":
		return cTemplate(lang, kind, name, imports)
	default:
		return genericTemplate(kind, name, imports)
	}
}

func importLines(prefix string, imports []string) string {
	var b strings.Builder
	for _, imp := range imports {
		imp = strings.TrimSpace(imp)
		if imp == "" {
			continue
		}
		fmt.Fprintf(&b, prefix+"\n", imp)
	}
	return b.String()
}

func goTemplate(kind, name, namespace string, imports []string) string {
	pkg := namespace
	if pkg == "" {
		pkg = "main"
	}
	var b strings.Builder
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range imports {
			imp = strings.TrimSpace(imp)
			if imp != "" {
				fmt.Fprintf(&b, "\t%q\n", imp)
			}
		}
		b.WriteString(")\n\n")
	}
	switch kind {
	case "interface":
		fmt.Fprintf(&b, "// %s is generated by meta-lattice scaffold.\ntype %s interface {\n\t// TODO: add methods\n}\n", name, name)
	default:
		fmt.Fprintf(&b, "// %s is generated by meta-lattice scaffold.\ntype %s struct{}\n\n// New%s creates a %s.\nfunc New%s() *%s {\n\treturn &%s{}\n}\n", name, name, name, name, name, name, name)
	}
	return b.String()
}

func pythonTemplate(kind, name string, imports []string) string {
	var b strings.Builder
	b.WriteString("\"\"\"Generated by meta-lattice scaffold.\"\"\"\n\n")
	for _, imp := range imports {
		imp = strings.TrimSpace(imp)
		if imp != "" {
			fmt.Fprintf(&b, "from %s import %s\n", imp, strings.Split(imp, ".")[len(strings.Split(imp, "."))-1])
		}
	}
	if len(imports) > 0 {
		b.WriteString("\n")
	}
	switch kind {
	case "module":
		fmt.Fprintf(&b, "def main():\n    \"\"\"TODO: implement.\"\"\"\n    raise NotImplementedError\n")
	default:
		fmt.Fprintf(&b, "class %s:\n    \"\"\"TODO: document.\"\"\"\n\n    def __init__(self):\n        raise NotImplementedError\n", name)
	}
	return b.String()
}

func tsTemplate(lang, kind, name string, imports []string) string {
	var b strings.Builder
	b.WriteString("// Generated by meta-lattice scaffold.\n")
	b.WriteString(importLines(`import ... from "%s";`, imports))
	if len(imports) > 0 {
		b.WriteString("\n")
	}
	switch kind {
	case "interface":
		fmt.Fprintf(&b, "export interface %s {\n  // TODO: add members\n}\n", name)
	case "module":
		fmt.Fprintf(&b, "export function main(): void {\n  // TODO: implement\n}\n")
	default:
		fmt.Fprintf(&b, "export class %s {\n  // TODO: implement\n}\n", name)
	}
	_ = lang
	return b.String()
}

func javaTemplate(kind, name, namespace string, imports []string) string {
	var b strings.Builder
	if namespace != "" {
		fmt.Fprintf(&b, "package %s;\n\n", namespace)
	}
	b.WriteString(importLines("import %s;", imports))
	if len(imports) > 0 {
		b.WriteString("\n")
	}
	decl := "class"
	if kind == "interface" {
		decl = "interface"
	} else if kind == "enum" {
		decl = "enum"
	}
	fmt.Fprintf(&b, "// Generated by meta-lattice scaffold.\npublic %s %s {\n    // TODO: implement\n}\n", decl, name)
	return b.String()
}

func kotlinTemplate(kind, name, namespace string, imports []string) string {
	var b strings.Builder
	if namespace != "" {
		fmt.Fprintf(&b, "package %s\n\n", namespace)
	}
	b.WriteString(importLines("import %s", imports))
	if len(imports) > 0 {
		b.WriteString("\n")
	}
	decl := "class"
	switch kind {
	case "interface":
		decl = "interface"
	case "object":
		decl = "object"
	case "enum":
		decl = "enum class"
	case "data":
		decl = "data class"
	}
	fmt.Fprintf(&b, "// Generated by meta-lattice scaffold.\n%s %s {\n    // TODO: implement\n}\n", decl, name)
	return b.String()
}

func csharpTemplate(kind, name, namespace string, imports []string) string {
	var b strings.Builder
	b.WriteString(importLines("using %s;", imports))
	if len(imports) > 0 {
		b.WriteString("\n")
	}
	if namespace == "" {
		namespace = "App"
	}
	decl := "class"
	switch kind {
	case "interface":
		decl = "interface"
	case "struct":
		decl = "struct"
	case "enum":
		decl = "enum"
	case "record":
		decl = "record"
	}
	fmt.Fprintf(&b, "// Generated by meta-lattice scaffold.\nnamespace %s;\n\npublic %s %s\n{\n    // TODO: implement\n}\n", namespace, decl, name)
	return b.String()
}

func swiftTemplate(kind, name string, imports []string) string {
	var b strings.Builder
	b.WriteString("// Generated by meta-lattice scaffold.\n")
	if len(imports) == 0 {
		b.WriteString("import Foundation\n")
	} else {
		b.WriteString(importLines("import %s", imports))
	}
	b.WriteString("\n")
	decl := "struct"
	if kind == "class" {
		decl = "class"
	} else if kind == "enum" {
		decl = "enum"
	} else if kind == "protocol" || kind == "interface" {
		decl = "protocol"
	}
	fmt.Fprintf(&b, "public %s %s {\n    // TODO: implement\n}\n", decl, name)
	return b.String()
}

func phpTemplate(kind, name, namespace string, imports []string) string {
	var b strings.Builder
	b.WriteString("<?php\n\ndeclare(strict_types=1);\n\n")
	if namespace != "" {
		fmt.Fprintf(&b, "namespace %s;\n\n", namespace)
	}
	b.WriteString(importLines("use %s;", imports))
	if len(imports) > 0 {
		b.WriteString("\n")
	}
	decl := "class"
	switch kind {
	case "interface":
		decl = "interface"
	case "trait":
		decl = "trait"
	case "enum":
		decl = "enum"
	}
	fmt.Fprintf(&b, "// Generated by meta-lattice scaffold.\n%s %s\n{\n    // TODO: implement\n}\n", decl, name)
	return b.String()
}

func rustTemplate(kind, name string, imports []string) string {
	var b strings.Builder
	b.WriteString("// Generated by meta-lattice scaffold.\n")
	b.WriteString(importLines("use %s;", imports))
	if len(imports) > 0 {
		b.WriteString("\n")
	}
	switch kind {
	case "enum":
		fmt.Fprintf(&b, "pub enum %s {\n    // TODO: add variants\n}\n", name)
	case "trait", "interface":
		fmt.Fprintf(&b, "pub trait %s {\n    // TODO: add methods\n}\n", name)
	default:
		fmt.Fprintf(&b, "pub struct %s;\n\nimpl %s {\n    pub fn new() -> Self {\n        Self\n    }\n}\n", name, name)
	}
	return b.String()
}

func cTemplate(lang, kind, name string, imports []string) string {
	var b strings.Builder
	b.WriteString("// Generated by meta-lattice scaffold.\n")
	b.WriteString(importLines("#include <%s>", imports))
	if len(imports) > 0 {
		b.WriteString("\n")
	}
	if lang == "cpp" {
		switch kind {
		case "interface":
			fmt.Fprintf(&b, "class %s {\npublic:\n    virtual ~%s() = default;\n    // TODO: add methods\n};\n", name, name)
		default:
			fmt.Fprintf(&b, "class %s {\npublic:\n    %s();\n    // TODO: implement\n};\n", name, name)
		}
	} else {
		fmt.Fprintf(&b, "typedef struct %s {\n    // TODO: add fields\n} %s;\n", name, name)
	}
	return b.String()
}

func genericTemplate(kind, name string, imports []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by meta-lattice scaffold: %s %s.\n", kind, name)
	for _, imp := range imports {
		imp = strings.TrimSpace(imp)
		if imp != "" {
			fmt.Fprintf(&b, "// import: %s\n", imp)
		}
	}
	b.WriteString("// TODO: implement\n")
	return b.String()
}
